kzero:
  home: /home/k0s
  # load balancer for api
  external_address: 192.168.0.67

  controller:
    # when adding another controller
    token: null
    token_expires: '1h'

  worker:
    # when adding worker nodes
    token: null
    token_expires: '0'